# vi:ts=4:sw=4:sts=4:et

stages:
    - test
    - build

test:
    stage: test
    image: alpine
    script:
        - apk add --no-cache bash
        - ci/test.sh

build:
    stage: build
    image: alpine
    script:
        - ci/build.sh
    artifacts:
        paths:
            - 'asciidoc-utils.sh'
