= asciidoc-utils

Some utilities for scripts outputting and/or manipulating asciidoc.

Should work in any posix compliant shell. The only dependency are posix shell
builtins and a posix compliant `awk` and `sed`

Tested with the following shells:

- dash (default sh for debian)
- busybox sh (default sh for alpine)
- bash
- loksh
- mksh
- zsh

Tested with the following implementations of `awk`:

- busybox awk (default for alpine)
- gnu awk

Tested with the following implementations of `sed`:

- busybox sed (default for alpine)
- gnu sed (default for debian)

If you find any shells or implementations of `awk` or `sed` that do not work or
which are not tested, please let me know by opening an issue (or pull request).

== Usage

```
export ASCIIDOC_UTILS_PATH=/path/to/src
. "$ASCIIDOC_UTILS_PATH/main.sh"
```

Depending on your shell it may not be neccesary to set `ASCIIDOC_UTILS_PATH`,
but this uses shell specific, non-posix and potentially non-portable code.

== Tests

The tests are written using https://github.com/sstephenson/bats[bats]. Acquire
bats and run `bats tests` to run the test suite.

