= asciidoc-utils

Some utilities for scripts outputting and/or manipulating asciidoc.

Should work in any posix compliant shell. The only dependency is a posix
compliant AWK.

Tested with the following shells:

- dash (default sh for debian)
- busybox sh (default sh for alpine)
- bash
- loksh
- mksh
- zsh

Tested with the following awks:

- busybox awk (default for alpine)
- gawk

If you find any shells or awks that it does not work in please let me know by
opening an issue. Additionally, if there are any common shells or awks that it
is not tested in that you would like to see added to the list, open an issue
(or pull request).

== Usage

```
export ASCIIDOC_UTILS_PATH=/path/to/src
. "$ASCIIDOC_UTILS_PATH/main.sh"
```

Depending on your shell it may not be neccesary to set `ASCIIDOC_UTILS_PATH`,
but this uses shell specific, non-posix and potentially non-portable code.

== Tests

The tests are written using https://github.com/sstephenson/bats[bats]. Acquire
bats and run `bats tests` to run the test suite.

